Imports ModelContextProtocol.Server
Imports System.ComponentModel
Imports System.IO
Imports System.Drawing
Imports System.Drawing.Imaging
Imports Newtonsoft.Json

Namespace Tools
    <McpServerToolType>
    Public Class SpriteTools

        Private Class CleanResult
            Public Property File As String
            Public Property OriginalSize As String
            Public Property FinalSize As String
            Public Property PixelsRemoved As Integer
            Public Property BackupCreated As Boolean
            Public Property SavedTo As String
        End Class

        <McpServerTool, Description("Cleans sprite PNG files generated by Gemini: removes white/gray border artifacts (residual dividing lines, anti-aliasing), auto-crops transparent padding. Creates .bak backup before overwriting. Supports single file or *.png batch.")>
        Public Shared Function B4aSpriteCleanup(
            <Description("Path to PNG file (e.g. C:\sprites\boss_f0.png) or glob for batch (e.g. C:\sprites\*.png)")> imagePath As String,
            <Description("Width in pixels of border strip to scan on each side for artifacts (default 4)")> Optional edgePx As Integer = 4,
            <Description("White threshold: border pixels with R, G and B all above this value are set to transparent (default 210)")> Optional whiteThreshold As Integer = 210,
            <Description("Gray threshold: border pixels that are near-neutral (low channel variance) and brighter than this are set to transparent (default 200)")> Optional grayThreshold As Integer = 200,
            <Description("Auto-crop transparent padding after edge cleanup (default true)")> Optional autoCrop As Boolean = True,
            <Description("Output path override. Leave empty to overwrite original with .bak backup first.")> Optional outputPath As String = ""
        ) As String
            Try
                Dim files As String()
                If imagePath.Contains("*") Then
                    Dim dir = Path.GetDirectoryName(imagePath)
                    Dim pat = Path.GetFileName(imagePath)
                    If String.IsNullOrEmpty(dir) Then dir = Directory.GetCurrentDirectory()
                    If Not Directory.Exists(dir) Then Return $"Error: directory not found: {dir}"
                    files = Directory.GetFiles(dir, pat)
                    If files.Length = 0 Then Return $"No files matched: {imagePath}"
                Else
                    If Not File.Exists(imagePath) Then Return $"Error: file not found: {imagePath}"
                    files = New String() {imagePath}
                End If

                Dim results = New List(Of CleanResult)()
                Dim totalPixels = 0

                For Each f In files
                    Dim r = CleanSingleSprite(f, edgePx, whiteThreshold, grayThreshold, autoCrop, outputPath)
                    results.Add(r)
                    totalPixels += r.PixelsRemoved
                Next

                If files.Length = 1 Then
                    Return JsonConvert.SerializeObject(results(0), Formatting.Indented)
                End If

                Return JsonConvert.SerializeObject(New With {
                    .filesProcessed = files.Length,
                    .totalPixelsRemoved = totalPixels,
                    .files = results
                }, Formatting.Indented)

            Catch ex As Exception
                Return $"Error: {ex.Message}"
            End Try
        End Function

        <McpServerTool, Description(
            "Slices a sprite sheet into individual frame PNGs by a cols×rows grid. Each cell becomes baseName_<index>.png " &
            "(row-major, 0-based). Frame size = sheetWidth/cols × sheetHeight/rows. Returns the frame size and the files written.")>
        Public Shared Function B4aSpriteSlice(
            <Description("Path to the sprite sheet PNG")> sheetPath As String,
            <Description("Number of columns in the grid")> cols As Integer,
            <Description("Number of rows in the grid")> rows As Integer,
            <Description("Output directory (default: <sheet>_frames next to the sheet)")> Optional outputDir As String = "",
            <Description("Base name for frames (default: the sheet filename)")> Optional baseName As String = ""
        ) As String
            If Not File.Exists(sheetPath) Then Return $"Error: file not found: {sheetPath}"
            If cols < 1 OrElse rows < 1 Then Return "Error: cols and rows must be >= 1"
            Try
                Dim files As New List(Of String)
                Dim fw As Integer, fh As Integer
                Using src = New Bitmap(New MemoryStream(File.ReadAllBytes(sheetPath)))
                    fw = src.Width \ cols
                    fh = src.Height \ rows
                    If fw < 1 OrElse fh < 1 Then Return $"Error: {cols}x{rows} grid is larger than the {src.Width}x{src.Height} sheet"

                    Dim outDir = If(String.IsNullOrWhiteSpace(outputDir),
                                    Path.Combine(Path.GetDirectoryName(sheetPath), Path.GetFileNameWithoutExtension(sheetPath) & "_frames"),
                                    outputDir)
                    Directory.CreateDirectory(outDir)
                    Dim bn = If(String.IsNullOrWhiteSpace(baseName), Path.GetFileNameWithoutExtension(sheetPath), baseName)

                    Dim idx = 0
                    For r = 0 To rows - 1
                        For c = 0 To cols - 1
                            Using frame = New Bitmap(fw, fh, PixelFormat.Format32bppArgb)
                                Using g = Graphics.FromImage(frame)
                                    g.DrawImage(src, New Rectangle(0, 0, fw, fh), New Rectangle(c * fw, r * fh, fw, fh), GraphicsUnit.Pixel)
                                End Using
                                Dim outPath = Path.Combine(outDir, $"{bn}_{idx}.png")
                                frame.Save(outPath, ImageFormat.Png)
                                files.Add(outPath)
                            End Using
                            idx += 1
                        Next
                    Next
                End Using

                Return JsonConvert.SerializeObject(New With {
                    .frameWidth = fw, .frameHeight = fh, .count = files.Count, .files = files
                }, Formatting.Indented)
            Catch ex As Exception
                Return $"Error: {ex.Message}"
            End Try
        End Function

        <McpServerTool, Description(
            "Packs multiple frame PNGs into a single atlas image on a uniform grid (cell = the largest frame), and writes a " &
            "JSON metadata sidecar (<atlas>.json) mapping each frame name to its {x, y, w, h} in the atlas. " &
            "inputGlob is a folder glob like C:\frames\*.png. columns=0 packs a single horizontal strip.")>
        Public Shared Function B4aSpritePack(
            <Description("Glob for the frame PNGs, e.g. C:\frames\*.png")> inputGlob As String,
            <Description("Output atlas PNG path")> outputPath As String,
            <Description("Columns in the atlas grid (0 = single horizontal strip)")> Optional columns As Integer = 0
        ) As String
            Try
                Dim dir = Path.GetDirectoryName(inputGlob)
                Dim pat = Path.GetFileName(inputGlob)
                If String.IsNullOrEmpty(dir) Then dir = Directory.GetCurrentDirectory()
                If Not Directory.Exists(dir) Then Return $"Error: directory not found: {dir}"
                Dim frameFiles = Directory.GetFiles(dir, pat).OrderBy(Function(f) f, StringComparer.Ordinal).ToArray()
                If frameFiles.Length = 0 Then Return $"No files matched: {inputGlob}"

                Dim frames As New List(Of (Name As String, Bmp As Bitmap))
                Try
                    Dim cellW = 0, cellH = 0
                    For Each f In frameFiles
                        Dim bmp = New Bitmap(New MemoryStream(File.ReadAllBytes(f)))
                        frames.Add((Path.GetFileNameWithoutExtension(f), bmp))
                        cellW = Math.Max(cellW, bmp.Width)
                        cellH = Math.Max(cellH, bmp.Height)
                    Next

                    Dim numCols = If(columns <= 0, frames.Count, columns)
                    Dim numRows = CInt(Math.Ceiling(frames.Count / CDbl(numCols)))

                    Dim meta As New List(Of Object)
                    Using atlas = New Bitmap(numCols * cellW, numRows * cellH, PixelFormat.Format32bppArgb)
                        Using g = Graphics.FromImage(atlas)
                            For i = 0 To frames.Count - 1
                                Dim cx = (i Mod numCols) * cellW
                                Dim cy = (i \ numCols) * cellH
                                g.DrawImage(frames(i).Bmp, cx, cy)
                                meta.Add(New With {.name = frames(i).Name, .x = cx, .y = cy, .w = frames(i).Bmp.Width, .h = frames(i).Bmp.Height})
                            Next
                        End Using
                        Dim outDir = Path.GetDirectoryName(outputPath)
                        If Not String.IsNullOrEmpty(outDir) Then Directory.CreateDirectory(outDir)
                        atlas.Save(outputPath, ImageFormat.Png)
                    End Using

                    Dim metaPath = outputPath & ".json"
                    Dim metaJson = JsonConvert.SerializeObject(New With {
                        .atlas = Path.GetFileName(outputPath), .cellWidth = cellW, .cellHeight = cellH,
                        .columns = numCols, .rows = numRows, .frames = meta
                    }, Formatting.Indented)
                    File.WriteAllText(metaPath, metaJson)

                    Return JsonConvert.SerializeObject(New With {
                        .atlasPath = outputPath, .metadataPath = metaPath,
                        .frameCount = frames.Count, .cellSize = $"{cellW}x{cellH}", .grid = $"{numCols}x{numRows}"
                    }, Formatting.Indented)
                Finally
                    For Each fr In frames
                        fr.Bmp.Dispose()
                    Next
                End Try
            Catch ex As Exception
                Return $"Error: {ex.Message}"
            End Try
        End Function

        Private Shared Function CleanSingleSprite(filePath As String, edgePx As Integer, whiteThreshold As Integer, grayThreshold As Integer, autoCrop As Boolean, outputDest As String) As CleanResult
            Dim origW As Integer, origH As Integer
            Dim pixelsRemoved = 0

            ' Load into 32-bit ARGB bitmap
            Dim argb As Bitmap
            Using fs = New FileStream(filePath, FileMode.Open, FileAccess.Read)
                Using raw = New Bitmap(fs)
                    origW = raw.Width
                    origH = raw.Height
                    argb = New Bitmap(origW, origH, PixelFormat.Format32bppArgb)
                    Using gfx = Graphics.FromImage(argb)
                        gfx.DrawImage(raw, 0, 0)
                    End Using
                End Using
            End Using

            ' Clamp edgePx to half the smaller dimension
            Dim ep = Math.Max(1, Math.Min(edgePx, Math.Min(origW, origH) \ 2))

            ' Edge artifact removal
            For py = 0 To origH - 1
                For px = 0 To origW - 1
                    Dim inEdge = (px < ep OrElse px >= origW - ep OrElse py < ep OrElse py >= origH - ep)
                    If Not inEdge Then Continue For

                    Dim c = argb.GetPixel(px, py)
                    If c.A = 0 Then Continue For

                    Dim cr = CInt(c.R)
                    Dim cg = CInt(c.G)
                    Dim cb = CInt(c.B)

                    Dim shouldRemove = False

                    ' White: all channels bright
                    If cr > whiteThreshold AndAlso cg > whiteThreshold AndAlso cb > whiteThreshold Then
                        shouldRemove = True
                    End If

                    ' Gray: near-neutral (low channel deviation) and bright
                    If Not shouldRemove Then
                        Dim avg = (cr + cg + cb) \ 3
                        Dim dev = Math.Abs(cr - avg) + Math.Abs(cg - avg) + Math.Abs(cb - avg)
                        ' dev/3 < 15 means average per-channel deviation < 15
                        If avg > grayThreshold AndAlso dev < 45 Then
                            shouldRemove = True
                        End If
                    End If

                    If shouldRemove Then
                        argb.SetPixel(px, py, Color.Transparent)
                        pixelsRemoved += 1
                    End If
                Next
            Next

            ' Auto-crop to content bounding box
            Dim saveBmp As Bitmap = argb
            If autoCrop Then
                Dim minX = origW, maxX = -1, minY = origH, maxY = -1
                For py = 0 To origH - 1
                    For px = 0 To origW - 1
                        If argb.GetPixel(px, py).A > 0 Then
                            If px < minX Then minX = px
                            If px > maxX Then maxX = px
                            If py < minY Then minY = py
                            If py > maxY Then maxY = py
                        End If
                    Next
                Next

                If maxX >= minX AndAlso maxY >= minY Then
                    Dim cw = maxX - minX + 1
                    Dim ch = maxY - minY + 1
                    Dim cropped = New Bitmap(cw, ch, PixelFormat.Format32bppArgb)
                    Using gfx = Graphics.FromImage(cropped)
                        gfx.DrawImage(argb, New Rectangle(0, 0, cw, ch), New Rectangle(minX, minY, cw, ch), GraphicsUnit.Pixel)
                    End Using
                    argb.Dispose()
                    saveBmp = cropped
                End If
            End If

            Dim finalW = saveBmp.Width
            Dim finalH = saveBmp.Height

            ' Backup original and save
            Dim savePath = If(String.IsNullOrEmpty(outputDest), filePath, outputDest)
            Dim backupCreated = False
            If String.IsNullOrEmpty(outputDest) Then
                Dim bakPath = filePath & ".bak"
                If Not File.Exists(bakPath) Then
                    File.Copy(filePath, bakPath)
                    backupCreated = True
                End If
            End If

            saveBmp.Save(savePath, ImageFormat.Png)
            saveBmp.Dispose()

            Return New CleanResult() With {
                .File = Path.GetFileName(filePath),
                .OriginalSize = $"{origW}x{origH}",
                .FinalSize = $"{finalW}x{finalH}",
                .PixelsRemoved = pixelsRemoved,
                .BackupCreated = backupCreated,
                .SavedTo = savePath
            }
        End Function

    End Class
End Namespace
